version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    #ports:
    #  - "3000:80"
    
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - frontend-build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"
      - "8090:8090"
      - "8443:8443"
    environment:
      - DISABLE_IPV6=false
    volumes:
      #- ./data:/data
      - nginx_data:/data
      #- ./nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  frontend-build:
  nginx_data:
  letsencrypt:

