version: '3.8'

services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER:-localhost}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changethis123}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:${POSTGRES_PASSWORD:-5432}"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
        DOMAIN: localhost
        ENVIRONMENT: local
        PROJECT_NAME: "Full Stack FastAPI Project"
        STACK_NAME: full-stack-fastapi-project
        BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost:3000,https://localhost:3000"
        SECRET_KEY: changethis123
        FIRST_SUPERUSER: devops@hng.tech
        FIRST_SUPERUSER_PASSWORD: devops#HNG11
        USERS_OPEN_REGISTRATION: "True"
        SMTP_HOST: ""
        SMTP_USER: ""
        SMTP_PASSWORD: ""
        EMAILS_FROM_EMAIL: info@example.com
        SMTP_TLS: "True"
        SMTP_SSL: "False"
        SMTP_PORT: 587
        POSTGRES_SERVER: db
        POSTGRES_PORT: 5432
        POSTGRES_DB: app
        POSTGRES_USER: app
        POSTGRES_PASSWORD: changethis123
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://backend:8000

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - DISABLE_IPV6=true
    volumes:
      #- ./data:/data
      - ./nginx_data:/data
      #- ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  nginx_data:
  letsencrypt:
